import type { Metadata } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  weight: ["600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://uniads.eu"),
  title: "UniAds — AI media buyer for SMB",
  description:
    "Voice-first AI media buyer. Replaces a local agency: launches Meta & Google campaigns from one voice message, audits before spend, and tracks live performance.",
  openGraph: {
    type: "website",
    url: "https://uniads.eu",
    siteName: "UniAds",
    title: "UniAds — AI media buyer for SMB",
    description:
      "Meta и Google голосом из Telegram. Заменяет агентство за €500–1500 — за €99.",
    locale: "ru_RU",
    // /opengraph-image is auto-generated by src/app/opengraph-image.tsx;
    // Next.js injects it as og:image at build time, so we don't list it.
  },
  twitter: {
    card: "summary_large_image",
    title: "UniAds — AI media buyer for SMB",
    description:
      "Meta и Google голосом из Telegram. Заменяет агентство за €500–1500 — за €99.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${geistSans.variable} ${geistMono.variable} ${bricolage.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        {children}
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
